import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from "react"
import NavBar from "../components/NavBar"
import ContactSocials from "../components/ContactSocials"


const HomePage: NextPage = () => {
  const [isDarkMode, setIsDarkMode] = useState(true);

  return (
  <div className={isDarkMode ? "dark" : ""} style={{
    background:
      "linear-gradient(90deg, rgba(23,23,23,1) 0%, rgba(52,51,50,1) 25%, rgba(52,51,50,1) 75%, rgba(23,23,23,1) 100%);"
  }}>
    <Head>
      <title>theoh</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="min-h-screen lg:border-l-8 lg:border-r-8 dark:border-black border-white lg:max-w-5xl dark:bg-neutral-900 bg-stone-300 m-auto text-zinc-800 dark:text-zinc-300">
      {/*nesting compenent test*/}
      <NavBar darkModeState={setIsDarkMode} isDark={isDarkMode}/>
      <h1>under construction</h1>

    </div>
    </div>
  );
}

export default HomePage